### ISSUE TITLE
Source code not the same as what's in the 1.0.0 dist + JSON.stringify errors

### ISSUE THREAD

**Issue by arimus** [MarcoMedrano/winston-transport-browserconsole#2]
Looks like there is a JSON.stringify in the distributed package, but not in this repository. Something that didn't get checked in perhaps?

Given the use of JSON.stringify (a non-safe for circular deps version), this is blowing up for some outputs. It's pretty common to log some of these raw objects in a browser environment, which the browser has no issues displaying / introspecting. It would be nice if you at the least allowed BrowserConsole to have an option that replaced the serialization (JSON.stringify) that it uses to get around this issue.

I'd submit a patch, but as mentioned this code doesn't seem to be tracking with the distribution on npmjs.com.

**Comment by MarcoMedrano** [comment]
Hey, yeah I removed the usage of JSON as it was a workaround... well seems i did publish before generate the distribution code. Just fixed it, pls update to version 1.0.1
`npm update winston-transport-browserconsole -S`

**Comment by MarcoMedrano** [comment]
I think it is fixed and we can close this issue now.
