### ISSUE TITLE
Uncaught ReferenceError: setImmediate is not defined

### ISSUE THREAD

**Issue by shawnlah** [MarcoMedrano/winston-transport-browserconsole#9]
I have tried [this solution](https://github.com/winstonjs/winston/issues/1354#issuecomment-426433071) but doesn't work anymore.

**Comment by rayfoss** [comment]
... adding 3 user maintained dependencies for semantic logs across an app is, a bit disheartening. It would be great if we could package winston into the browser transport... there is little overlap with browserside use and server side use.

Perhaps we could grab the React and Vue crowd which are desperate for decent consistent logs across first party modules.
